Demo.Pl/Controllers/DepartmentsController.cs
using AutoMapper;
using Demo.BLL.Interfaces;
using Demo.DAL.Entities;
using Demo.Pl.Consts;
using Demo.Pl.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Demo.Pl.Controllers
{
    [Authorize]
    public class DepartmentsController : Controller
    {
        public IUnitOfWork UnitOfWork { get; }
        public IMapper mapper { get; }

       public DepartmentsController(IUnitOfWork unitOfWork, IMapper mapper)
        {
            UnitOfWork = unitOfWork;
            this.mapper = mapper;
        }

        public async Task<IActionResult> Index(string SearchValue)
        {
            if (string.IsNullOrEmpty(SearchValue)) {
             var departments = await UnitOfWork.departmentRepository.GetAll();
            var departmentsViewModel = mapper.Map<IEnumerable<Department> , IEnumerable<DepartmentViewModel>>(departments);
            return View(departmentsViewModel);

            }
           
            var SearchedDepartments=await UnitOfWork.departmentRepository.SearchByDepartmentName(SearchValue);
            var SearchedDepartmentsViewModel= mapper.Map<IEnumerable<Department>, IEnumerable<DepartmentViewModel>>(SearchedDepartments);
            return View(SearchedDepartmentsViewModel);

        }
        public IActionResult Create()
        {

            return View("Form");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(DepartmentViewModel departmentViewModel)
        {
            if (ModelState.IsValid)
            {  // Server Side Validation
                var department = mapper.Map<DepartmentViewModel, Department>(departmentViewModel);
                await UnitOfWork.departmentRepository.Add(department);
                return RedirectToAction(nameof(Index));
            }

            return View("Form", departmentViewModel);

        }
        public  async Task <IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            var department = await UnitOfWork.departmentRepository.Get(id);
            if (department is null)

                return NotFound();
            var departmentViewModel = mapper.Map<Department, DepartmentViewModel>(department);

            return View(departmentViewModel);

        }
        public async Task <IActionResult> Edit(int? id) {

            if (id == null)
                return NotFound();

            var department = await UnitOfWork.departmentRepository.Get(id);
            if (department is null)

                return NotFound();
            var departmentViewModel = mapper.Map<Department, DepartmentViewModel>(department);

            return View("Form", departmentViewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task <IActionResult> Edit(DepartmentViewModel departmentViewModel)
        {
            if (!ModelState.IsValid) {
                return View("Form", departmentViewModel);
            }
            var department = mapper.Map<DepartmentViewModel, Department>(departmentViewModel);

            await UnitOfWork.departmentRepository.Update(department);
            return RedirectToAction(nameof(Index) , departmentViewModel);     
        }
        public async Task<IActionResult> Delete(int? id) {
            if (id == null)
                return NotFound();
            var department = await UnitOfWork.departmentRepository.Get(id);
            if(department is null)
                return NotFound();
            var departmentViewModel = mapper.Map<Department, DepartmentViewModel>(department);

            return View(departmentViewModel);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(DepartmentViewModel departmentViewModel) {
            var department = mapper.Map<DepartmentViewModel, Department>(departmentViewModel);


           await UnitOfWork.departmentRepository.Delete(department);
            return RedirectToAction(nameof(Index));
        }

    }
}

Demo.Pl/Controllers/EmployeesController.cs
using AutoMapper;
using Demo.BLL.Interfaces;
using Demo.BLL.Repositories;
using Demo.DAL.Entities;
using Demo.Pl.Consts;
using Demo.Pl.Helper;
using Demo.Pl.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Demo.Pl.Controllers
{
    [Authorize]

    public class EmployeesController : Controller
    {

   
        public IMapper mapper { get; }
        public IUnitOfWork UnitOfWork { get; }

        public EmployeesController(IMapper mapper , IUnitOfWork unitOfWork)
        {
   
            this.mapper = mapper;
            UnitOfWork = unitOfWork;
        }


        public async Task<IActionResult> Index(string searchValue)
        {
            if (string.IsNullOrEmpty(searchValue)){      
            var employees = await UnitOfWork.employeeRepository.GetAll();
            var employeesViewModel = mapper.Map<IEnumerable<Employee>, IEnumerable<EmployeeViewModel>>(employees);
                return View(employeesViewModel);
            }

            var SearchedEmployees = await UnitOfWork.employeeRepository.SearchByEmplyeeName(searchValue);
            var SearchedEmployeesViewModel = mapper.Map<IEnumerable<Employee>, IEnumerable<EmployeeViewModel>>(SearchedEmployees);


            return View(SearchedEmployeesViewModel);
        }
        public async Task<IActionResult> Create()
        {
            ViewBag.Departments = await UnitOfWork.departmentRepository.GetAll();
            return View("Form");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EmployeeViewModel employeeViewModel)
        {
            if (ModelState.IsValid)
            {  // Server Side Validation
                employeeViewModel.ImageName = DocumentSettings.UploadFile(employeeViewModel.Image, "images");
                var employee = mapper.Map<EmployeeViewModel, Employee>(employeeViewModel);
                await UnitOfWork.employeeRepository.Add(employee);
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Departments = await UnitOfWork.departmentRepository.GetAll();

            return View("Form", employeeViewModel);

        }
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            var employee = await UnitOfWork.employeeRepository.Get(id);
            if (employee is null)

                return NotFound();
            ViewBag.Departments = await UnitOfWork.departmentRepository.GetAll();
            var employeeViewModel =mapper.Map<Employee, EmployeeViewModel>(employee);

            return View(employeeViewModel);

        }
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var employee = await UnitOfWork.employeeRepository.Get(id);
            if (employee is null)

                return NotFound();
            ViewBag.Departments = await UnitOfWork.departmentRepository.GetAll();
            var employeeViewModel = mapper.Map<Employee, EmployeeViewModel>(employee);

            return View("Form", employeeViewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EmployeeViewModel employeeViewModel)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Departments = await UnitOfWork.departmentRepository.GetAll();

                return View("Form", employeeViewModel);
            }
            employeeViewModel.ImageName = DocumentSettings.UploadFile(employeeViewModel.Image, "images");

            var employee = mapper.Map<EmployeeViewModel, Employee>(employeeViewModel);

            await UnitOfWork.employeeRepository.Update(employee);
            return RedirectToAction(nameof(Index), employeeViewModel);
        }
        [Authorize(Roles = Role.Admin)]

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();
            var employee = await UnitOfWork.employeeRepository.Get(id);
            if (employee is null)
                return NotFound();
            var employeeViewModel = mapper.Map<Employee, EmployeeViewModel>(employee);
            ViewBag.Departments = await UnitOfWork.departmentRepository.GetAll();

            return View(employeeViewModel);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(EmployeeViewModel employeeViewModel)
        {
         
            var employee = mapper.Map<EmployeeViewModel, Employee>(employeeViewModel);


            if (employeeViewModel.ImageName != null)
            {
                DocumentSettings.DeleteFile(employeeViewModel.ImageName, "images");

            }
            await UnitOfWork.employeeRepository.Delete(employee);
            return RedirectToAction(nameof(Index));
        }
    }
}

Demo.Pl/Controllers/UsersController.cs
using Demo.DAL.Entities;
using Demo.Pl.Consts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;

namespace Demo.Pl.Controllers
{
    [Authorize(Roles =Role.Admin)]
    public class UsersController : Controller
    {

        public UserManager<ApplicationUser> UserManager { get; }


        public UsersController(UserManager<ApplicationUser> userManager)
        {
            UserManager = userManager;
        }


        public async Task<IActionResult> Index(string searchValue)
        {
            if (string.IsNullOrEmpty(searchValue))
            {
                var users = await UserManager.Users.ToListAsync();
                return View(users);

            }
            var searchedUser = await UserManager.FindByEmailAsync(searchValue);
         
             return View(new List<ApplicationUser>() { searchedUser });

         
        }
        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
                return NotFound();
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
                return NotFound();
            return View(user);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(ApplicationUser updatedUser)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByIdAsync(updatedUser.Id);
                user.UserName = updatedUser.UserName;
                user.NormalizedUserName = updatedUser.UserName.ToUpper();
                user.PhoneNumber = updatedUser.PhoneNumber;
                await UserManager.UpdateAsync(user);
                return RedirectToAction(nameof(Index));
            }
            return View(updatedUser);

        }
        [HttpGet]

        public async Task<IActionResult> Delete(string? id)
        {
            if (id == null)
                return NotFound();
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
                return NotFound();
            return View(user);
        }
        [HttpPost]

        public async Task<IActionResult> Delete(ApplicationUser deletedUser)
        {

            var user = await UserManager.FindByIdAsync(deletedUser.Id);
            var isDeleted = await UserManager.DeleteAsync(user);
            if (isDeleted.Succeeded)
                return RedirectToAction(nameof(Index));

            foreach (var error in isDeleted.Errors)

                ModelState.AddModelError(string.Empty, error.Description);

            return View(deletedUser);

        }


    }
}

Demo.Pl/Views/Shared/_AuthenticationLayout.cshtml
<!--
Author: Colorlib
Author URL: https://colorlib.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
	<title>@ViewData["Title"]</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
	<!-- Custom Theme files -->
	<link href="~/css/stylecss.css" rel="stylesheet" type="text/css" media="all" />
	<!-- //Custom Theme files -->
	<!-- web font -->
	<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
	<!-- //web font -->
</head>
<body>
	<!-- main -->
	<div class="main-w3layouts wrapper">
		<h1>@ViewData["Title"]</h1>
		@RenderBody()
		<!-- copyright -->
		<div class="colorlibcopy-agile">
			<p>© 2018 Colorlib Signup Form. All rights reserved | Design by <a href="https://colorlib.com/" target="_blank">Colorlib</a></p>
		</div>
		<!-- //copyright -->
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
	<!-- //main -->
</body>
</html>

Demo.Pl/Views/Shared/_AuthenticationLayout2.cshtml
<!DOCTYPE html>
<!-- Coding By CodingNepal - youtube.com/codingnepal -->
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/AuthenticationLayoutStylecss.css">
</head>
<body>
    <div class="center">
        <h1>@ViewData["Title"]</h1>
        @RenderBody()
    </div>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Demo.Pl/Views/Shared/_ButtonsPartial.cshtml
<td>

    <a  asp-action="Details" asp-route-id="@Model" class="btn btn-info btn-sm">
     Details
        <i class="fas fa-eye"></i>
    </a>

</td>
<td>

    <a  asp-action="Edit" asp-route-id="@Model" class="btn btn-primary btn-sm">
   Edit
        <i class="fas fa-edit"></i>
    </a>

</td>
<td>

    <a  asp-action="Delete" asp-route-id="@Model"class="btn btn-danger btn-sm">
      Delete
        <i class="fas fa-trash"></i>
    </a>

</td>

Demo.Pl/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Demo.Pl</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Demo.Pl.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Demo.Pl</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light "  asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light " asp-controller="Departments" asp-action="Index">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light " asp-controller="Employees" asp-action="Index">Employees</a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link text-light " asp-controller="Users" asp-action="Index">Users</a>
                        </li>
                    </ul>
                <partial name="_Register&LogoutLinks"/>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Demo.Pl - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Demo.Pl/Views/Shared/_Register&LogoutLinks.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<ul class="navbar-nav">
    @if (SignInManager.IsSignedIn(User))
    {
        <li class="nav-item">
            <a id="manage" class="nav-link text-white" title="Manage">Hello @UserManager.GetUserName(User)!</a>
        </li>
        <li class="nav-item">
            <a id="manage" class="nav-link text-white" asp-controller="Accounts" asp-action="SignOut"> SignOut</a>
        </li>
    }
 
</ul>